cat <<EOF > docker-compose.yml
version: '3.8'

services:
  backend:
    image: ${{ secrets.DOCKER_HUB_USERNAME }}/peeny-backend:latest
    restart: unless-stopped
    environment:
      DB_HOST: 93.127.206.203
      DB_USER: ptadmin
      DB_PASSWORD: iE6IApsCDfNsVAdurDdK
      DB_NAME: peenytoolsdb
      DB_PORT: 3306
      JWT_SECRET: pennytools-ai-shopfront-secure-jwt-secret-key-2024
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    image: ${{ secrets.DOCKER_HUB_USERNAME }}/peeny-frontend:latest
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://backend:3000
    depends_on:
      - backend
    expose:
      - "80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
EOF
