name: CI/CD – PEENYTOOLS

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/peeny-backend:latest

      - name: Build & push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/peeny-frontend:latest

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Prepare SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/peeny-backend:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/peeny-frontend:latest

            # Write docker-compose.yml file on the server
            cat <<EOF > docker-compose.yml
            version: '3.8'

            services:
              backend:
                image: ${{ secrets.DOCKER_HUB_USERNAME }}/peeny-backend:latest
                restart: unless-stopped
                environment:
                  DB_HOST: 93.127.206.203
                  DB_USER: ptadmin
                  DB_PASSWORD: iE6IApsCDfNsVAdurDdK
                  DB_NAME: peenytoolsdb
                  DB_PORT: 3306
                  JWT_SECRET: pennytools-ai-shopfront-secure-jwt-secret-key-2024
                ports:
                  - "3000:3000"
                networks:
                  - app-network

              frontend:
                image: ${{ secrets.DOCKER_HUB_USERNAME }}/peeny-frontend:latest
                restart: unless-stopped
                environment:
                  VITE_API_BASE_URL: http://localhost:3000
                depends_on:
                  - backend
                expose:
                  - "80"
                networks:
                  - app-network

            networks:
              app-network:
                driver: bridge
            EOF

            # Use docker compose to bring everything up
            docker compose down
            docker compose up -d
